drop table member
;
-- 시퀀스도 생성했음. 참고바람

-- 트리거 생성
CREATE TRIGGER member_trigger
BEFORE INSERT ON member
FOR EACH ROW
BEGIN
  SELECT member_seq.NEXTVAL INTO :new.id FROM dual;
END;

--
create table member (
   id number(15) --generated by default as identity,
  ,name varchar(255)
  ,constraint member_pk primary key (id)
);

commit;